name: TEST NPOI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  RUN-WINDOWS-TESTS:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    
    - name: ADD msbuild TO PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: SETUP .NET SDKs
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: | 
          3.1.x
          6.0.x
          
    - name: RESTORE NPOI.Multitarget.Test NUGET PACKAGES
      run: dotnet restore solution/NPOI.Multitarget.Test.sln
      
    - name: BUILD NPOI.Multitarget.Test.sln
      id: build-npoi
      run: >-
        dotnet build solution/NPOI.Multitarget.Test.sln
        --no-restore
        --configuration 'Debug'
        --verbosity q
      
    - name: RUN .NET 6 NPOI.Multitarget.TestCases
      if: always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/main/bin/Debug/net6.0/NPOI.TestCases.dll
        --configuration 'Debug'
        --settings ./test.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.TestCases.net6.trx'
        --results-directory test-results
      
    - name: RUN .NET 6 NPOI.OOXML.Multitarget.Testcases
      if : always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/ooxml/bin/Debug/net6.0/NPOI.OOXML.TestCases.dll
        --configuration 'Debug'
        --settings ./test.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.OOXML.TestCases.net6.trx'
        --results-directory test-results
      
    - name: RUN .NET 6 NPOI.OOXML4Net.Multitarget.TestCases
      if: always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/openxml4net/bin/Debug/net6.0/NPOI.OOXML4Net.TestCases.dll
        --configuration 'Debug'
        --settings ./test.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.OOXML4Net.TestCases.net6.trx'
        --results-directory test-results
      
    - name: PUBLISH TEST RESULTS
      uses: dorny/test-reporter@v1
      if: always() && steps.build-npoi.outcome == 'success'
      with:
        path: 'test-results/*.trx'
        name: NPOI .NET 6 Windows Test Results
        reporter: 'dotnet-trx'

  RUN-UBUNTU-TESTS:    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: SETUP .NET SDKs
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: | 
          3.1.x
          6.0.x
          
    - name: RESTORE NPOI.Multitarget.Test NUGET PACKAGES
      run: dotnet restore solution/NPOI.Multitarget.Test.sln
      
    - name: BUILD NPOI.Multitarget.Test.sln
      id: build-npoi
      run: >-
        dotnet build solution/NPOI.Multitarget.Test.sln
        --no-restore
        --configuration 'Debug'
        --verbosity q
   
    - name: PWD
      run: pwd
   
    - name: RUN .NET 6 NPOI.Multitarget.TestCases
      if: always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/main/bin/Debug/net6.0/NPOI.TestCases.dll
        --configuration 'Debug'
        --settings ./testcases/ubuntu.workflow.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.TestCases.trx'
        --results-directory test-results
      
    - name: RUN .NET 6 NPOI.OOXML.Multitarget.Testcases
      if : always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/ooxml/bin/Debug/net6.0/NPOI.OOXML.TestCases.dll
        --configuration 'Debug'
        --settings ./testcases/ubuntu.workflow.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.OOXML.TestCases.trx'
        --results-directory test-results
      
    - name: RUN .NET 6 NPOI.OOXML4Net.Multitarget.TestCases
      if: always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/openxml4net/bin/Debug/net6.0/NPOI.OOXML4Net.TestCases.dll
        --configuration 'Debug'
        --settings ./testcases/ubuntu.workflow.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.OOXML4Net.TestCases.trx'
        --results-directory test-results
    
    - name: PUBLISH TEST RESULTS
      uses: dorny/test-reporter@v1
      if: always() && steps.build-npoi.outcome == 'success'
      with:
        path: 'test-results/*.trx'
        name: NPOI .NET 6 Ubuntu Test Results
        reporter: 'dotnet-trx'

  RUN-MACOS-TESTS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: SETUP .NET SDKs
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: | 
          3.1.x
          6.0.x
          
    - name: RESTORE NPOI.Multitarget.Test NUGET PACKAGES
      run: dotnet restore solution/NPOI.Multitarget.Test.sln
      
    - name: BUILD NPOI.Multitarget.Test.sln
      id: build-npoi
      run: >-
        dotnet build solution/NPOI.Multitarget.Test.sln
        --no-restore
        --configuration 'Debug'
        --verbosity q

    - name: PWD
      run: pwd
   
    - name: RUN .NET 6 NPOI.Multitarget.TestCases
      if: always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/main/bin/Debug/net6.0/NPOI.TestCases.dll
        --configuration 'Debug'
        --settings ./testcases/macos.workflow.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.TestCases.trx'
        --results-directory test-results
      
    - name: RUN .NET 6 NPOI.OOXML.Multitarget.Testcases
      if : always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/ooxml/bin/Debug/net6.0/NPOI.OOXML.TestCases.dll
        --configuration 'Debug'
        --settings ./testcases/macos.workflow.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.OOXML.TestCases.trx'
        --results-directory test-results
      
    - name: RUN .NET 6 NPOI.OOXML4Net.Multitarget.TestCases
      if: always() && steps.build-npoi.outcome == 'success'
      run: >-
        dotnet test testcases/openxml4net/bin/Debug/net6.0/NPOI.OOXML4Net.TestCases.dll
        --configuration 'Debug'
        --settings ./testcases/macos.workflow.runsettings
        --verbosity q
        --logger 'trx;logfilename=NPOI.OOXML4Net.TestCases.trx'
        --results-directory test-results
      
    - name: PUBLISH TEST RESULTS
      uses: dorny/test-reporter@v1
      if: always() && steps.build-npoi.outcome == 'success'
      with:
        path: 'test-results/*.trx'
        name: NPOI .NET 6 macOS Test Results
        reporter: 'dotnet-trx'
